# =====================================================
# Car Cloud - Job 定时任务服务
# 生产环境配置 (prod)
# =====================================================

server:
  port: 9003

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka.car.com:8761/eureka/}

logging:
  level:
    root: WARN
