# =====================================================
# Car Cloud - Job 定时任务服务
# 预生产环境配置 (preprod)
# =====================================================

server:
  port: 9003

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-preprod.car.local:8761/eureka/

logging:
  level:
    root: WARN
